language: python
cache: pip
python:
  - 3.5
# command to install dependencies
install: make install
# command to run tests
script: make test
notifications:
  webhooks: https://mattermost.pubgem.com/hooks/xtrddiopcifop8w6oo1hh8nxsh
